[project]
name = "outfitadviser"
version = "0.1.0"
description = "This solution will save your time by planning outfits for you by referencing the pile of clothes you have"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
